# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03e661d0330f5bdcb0f0e59377554a3b093abc830a2c07c3c8ffd9392e38f2da198a345095fcfcb682920846a21a7bf822e0473f9a1e87d83f2e3fe61415ec9

test:
  secret_key_base: e4a51df33d64a37d32ddf5085bd0c9819e61f455d6828136d761e1f6a7dbc0e108b8abccd85b3ec427a37a51d1897229e757f8f5a0da785e588580472f331247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
